In [8]:
# Cuffling , plotly packages are also used but mostly we use numpy , Pandas, Matplotlib, Seaborn,etc

In [10]:
#Numpy is used to perform mathematical operations it is numeric python , they are extremly fast
import numpy as np
data = [10,20,30,40]
type(data)

list

In [12]:
np.array(data)

array([10, 20, 30, 40])

In [14]:
type(data)

list

In [16]:
arr = np.array(data)
type(arr)

numpy.ndarray

In [18]:
arr

array([10, 20, 30, 40])

In [20]:
np.random.rand(10)   #This is the method which will provide the random numbers from uniform distribution(values between 0 and 1)
#Here rand(10) will print 10 random values.It will provide uniform distribution
#this will give 1D array 


array([0.86652774, 0.15782849, 0.94053102, 0.80019916, 0.05203858,
       0.703324  , 0.46403532, 0.73912449, 0.15076467, 0.7483304 ])

In [22]:
np.random.rand(4,5) #This will give 2D arrays

array([[0.93660997, 0.5943268 , 0.20847152, 0.06903853, 0.87321981],
       [0.71445857, 0.82058866, 0.38995588, 0.14093116, 0.02331667],
       [0.39518151, 0.77832588, 0.03524216, 0.52849693, 0.79500579],
       [0.04937838, 0.09950977, 0.19463018, 0.81073205, 0.78585301]])

In [26]:
np.random.randn(12) #Here we will get the data from standard normal distribution formate  (means mean is 0 and standard deviation is 1)
#It will provide values 68% of the data lies between 0 to 1, 95% lies between , 98% lies between -3 to 3


array([-0.88756307,  2.04167698, -0.17526713,  0.43009223,  0.45881561,
        0.10102101,  0.58642181, -0.11712915,  0.5105335 ,  0.83034768,
       -0.57772851, -0.02938928])

In [30]:
np.random.randn(4,2)

array([[-0.96952197,  1.22103969],
       [ 0.33816708, -0.15519476],
       [ 0.44233161, -1.06039338],
       [ 0.46540594,  0.51296615]])

In [32]:
np.random.randint(1) #it will give random integers(starts form 0 )

0

In [34]:
np.random.randint(2,10) #Gives the random integer between 2 to 10

7

In [36]:
np.random.randint(15,25,6) # Gives 6 random integers between 15 to 25

array([19, 15, 22, 23, 15, 17])

In [40]:
arr1 = np.arange(10) #It will generate the array of given range
type(arr1)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr2 = np.arange(10,100,10)
print(arr2)

[10 20 30 40 50 60 70 80 90]


In [48]:
#reshape() method will help to change the shape of an array
np.arange(1,26).reshape(1,25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [50]:
np.arange(1,26).reshape(25,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [52]:
np.linspace(100,1000,100)

array([ 100.        ,  109.09090909,  118.18181818,  127.27272727,
        136.36363636,  145.45454545,  154.54545455,  163.63636364,
        172.72727273,  181.81818182,  190.90909091,  200.        ,
        209.09090909,  218.18181818,  227.27272727,  236.36363636,
        245.45454545,  254.54545455,  263.63636364,  272.72727273,
        281.81818182,  290.90909091,  300.        ,  309.09090909,
        318.18181818,  327.27272727,  336.36363636,  345.45454545,
        354.54545455,  363.63636364,  372.72727273,  381.81818182,
        390.90909091,  400.        ,  409.09090909,  418.18181818,
        427.27272727,  436.36363636,  445.45454545,  454.54545455,
        463.63636364,  472.72727273,  481.81818182,  490.90909091,
        500.        ,  509.09090909,  518.18181818,  527.27272727,
        536.36363636,  545.45454545,  554.54545455,  563.63636364,
        572.72727273,  581.81818182,  590.90909091,  600.        ,
        609.09090909,  618.18181818,  627.27272727,  636.36363

In [60]:
arr3=np.arange(1,21).reshape(4,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [64]:
arr3.shape

(4, 5)

In [66]:
#to get 9and14 from the matrix
arr3[[1,2],3]

array([ 9, 14])

In [68]:
arr3[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [74]:
arr3[1,1:4] #arr3[1:2,1:4]

array([7, 8, 9])

In [78]:
arr3[2:4,2:4] # to fetch 13,14,18,19

array([[13, 14],
       [18, 19]])

In [84]:
arr3[0:4,4:5]# or arr3[:,4:5]

array([[ 5],
       [10],
       [15],
       [20]])

In [86]:
#To fetch adjacent 2 and 19 from an array
arr3[[0,3],[1,3]]

array([ 2, 19])

In [88]:
arr3[[1,3],[3,3]]

array([ 9, 19])

In [90]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [102]:
np.arange(0,10,1).reshape(10,10)

ValueError: cannot reshape array of size 10 into shape (10,10)

In [116]:
np.arange(0,10).reshape(-1,1)*np.ones((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [124]:
#Broadcasting means it is some changes in subset of the original array for examples
arr=np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [126]:
arr_subset = arr(1,5)

TypeError: 'numpy.ndarray' object is not callable

In [128]:
#to get sum of an array
arr.sum()

325

In [132]:
arr4 = np.arange(1,26).reshape(5,5)
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [136]:
#to get the sum of first column in matrix
arr4[:,0].sum()

55

In [144]:
arr4.sum(axis=0) #axis = 0 means row and axis = 1mean column


array([55, 60, 65, 70, 75])

In [142]:
arr4.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [ ]:
#Kahoot it :it is online platform 