In [1]:
import numpy as np #np is alias

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
arr = np.array((1,2,3,4,5,6))#If we pass tuple then alsoo it gives array in numPy
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [19]:
arr = np.array(20)
print(arr)
print(type(arr))
print("The dimension is : ",arr.ndim)#ndim gives dimension

20
<class 'numpy.ndarray'>
The dimension is :  0


In [21]:
#1-Dimension array
arr = np.array([1,2,3,4,5])
print(arr)
print("the dimension is : ",arr.ndim)

[1 2 3 4 5]
the dimension is :  1


In [23]:
#2-Dimension Array 
arr = np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr)
print("The Dimensions are : ",arr.ndim)

[[1 2 3 4 5]
 [4 5 6 7 8]]
The Dimensions are :  2


In [27]:
#3-Dimension Array
arr = np.array([[[1,2,3,4],[2,3,4,5]],[[1,2,3,9],[6,7,8,9]]])
print(arr)
print("The Dimension of array is : ",arr.ndim)

[[[1 2 3 4]
  [2 3 4 5]]

 [[1 2 3 9]
  [6 7 8 9]]]
The Dimension of array is :  3


In [37]:
#Get third and sixth and 8th elements from the following array and add them.
arr = np.array([[1,23,4,5],[10,8,6,7]])
print("2nd element of first row : ",arr[0,1])
print("2nd element of second row :",arr[1,1])

2nd element of first row :  23
2nd element of second row : 8


In [45]:
#Access 3-D arrays we use comma separated integers representing the dimensions and the index of the element
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])
print(arr)
print("The 3rd element of the 2nd array of the 1st array :",arr[0,1,2])
print("The 4th element of the 2nd array of 2nd array :", arr[1,1,3])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [50 60 70 80]]]
The 3rd element of the 2nd array of the 1st array : 7
The 4th element of the 2nd array of 2nd array : 80


In [60]:
#slicing of numpy arrays
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[::2])

[2 3 4 5]
[1 3 5 7]


In [68]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0,1:5])


[7 8 9]
[2 3 4 5]


In [74]:
arr = np.array([[[12,33,4,5,9],[1,2,3,4,5]],[[6,7,8,9,9],[4,5,6,7,8]]])
print(arr[1,1,1:3])
print(arr[1,0,0:4])
print(arr[0,1,2:5])

[5 6]
[6 7 8 9]
[3 4 5]


In [76]:
#Checking the  datatype of an array
arr = np.array([1,2,3,4,5,5])
print(arr.dtype)

int32


In [78]:
arr = np.array([[1,2,3,4,5],[45,6,7,7,8]])
print(arr.dtype)

int32


In [80]:
arr= np.array(["animals", "Bat","Birds","fruits"])
print(arr.dtype)

<U7


In [84]:
#Creating arrays with a define datatypes
arr = np.array([1,2,3,4], dtype = 'S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [88]:
#Create an array with datatype 4 bytes integers
arr = np.array([1,2,3,4,5], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [92]:
arr = np.array([[1,2,3,3,4],[6,7,8,9,5]])
print(arr.shape)

(2, 5)


In [94]:
#Joining Numpy Arrays
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr =  np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [104]:
#Joining 2-D arrays
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[10,11,12,13],[1,2,3,4]])
arr3 = np.concatenate((arr1, arr2),axis = 1)#for axis = 1 concatenation is along row side
arr4 = np.concatenate((arr1, arr2),axis = 0)#for axis = 0 concatenation is column wise
print("for axis = 1: ",arr3)
print("for axis = 0: ",arr4)

for axis = 1:  [[ 1  2  3  4 10 11 12 13]
 [ 5  6  7  8  1  2  3  4]]
for axis = 0:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [10 11 12 13]
 [ 1  2  3  4]]


In [112]:
#splitting the array in 3 parts
arr = np.array([1,2,3,4,5,6])
newarr1 = np.array_split(arr,3)
newarr2 = np.array_split(arr,4)
print(newarr1)
print(newarr2)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [114]:
m = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(m)
print("The Dimension :",m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is ", n.ndim)

[[1 2 3 4 5]
 [5 6 7 8 9]]
The Dimension : 2
[1 2 3 4 5 5 6 7 8 9]
now the new dimension is  1


In [116]:
m = np.array([[[1,2,3,4],[3,4,5,6]],[[4,5,6,7],[5,6,7,8]]])
print(m)
print("The dimension : ", m.ndim)
n = m.ravel()
print(n)
print("The dimension : ", n.ndim)

[[[1 2 3 4]
  [3 4 5 6]]

 [[4 5 6 7]
  [5 6 7 8]]]
The dimension :  3
[1 2 3 4 3 4 5 6 4 5 6 7 5 6 7 8]
The dimension :  1


In [6]:
m = np.array([[1,2,3,4],[5,6,7,8]])
print(m)
print("The dimension : ",m.ndim)
n = m.ravel()
print(n)
print("The Dimension is : ",n.ndim)

[[1 2 3 4]
 [5 6 7 8]]
The dimension :  2
[1 2 3 4 5 6 7 8]
The Dimension is :  1


In [68]:
arr = np.array([[12,1,4,3],[36,7,7,4]])
print(arr)
print(arr.ndim)
n = arr.flatten()
print(n)
print(n.ndim)

[[12  1  4  3]
 [36  7  7  4]]
2
[12  1  4  3 36  7  7  4]
1


In [70]:
arr = np.array([[[[1,2,3,4],[4,5,6,7],[5,6,7,8]]]])
print(arr)
print(arr.ndim)
n = arr.flatten()
print(n)
print(n.ndim)


[[[[1 2 3 4]
   [4 5 6 7]
   [5 6 7 8]]]]
4
[1 2 3 4 4 5 6 7 5 6 7 8]
1


In [72]:
#Unique Function
arr = np.array([1,2,3,4,2,3,4,5,6,3,3,8,0,6,7])
print(arr)
new_array = np.unique(arr)
print(new_array)

[1 2 3 4 2 3 4 5 6 3 3 8 0 6 7]
[0 1 2 3 4 5 6 7 8]


In [82]:
arr = np.array([1,2,3,4,2,3,4,5,6,3,3,8,0,6,7])
print(arr)
new_array = np.unique(arr, return_index = True)
print(new_array)

[1 2 3 4 2 3 4 5 6 3 3 8 0 6 7]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([12,  0,  1,  2,  3,  7,  8, 14, 11], dtype=int64))


In [86]:
arr = np.array([1,2,3,4,2,3,4,5,6,3,3,8,0,6,7])
print(arr)
new_array = np.unique(arr, return_index=True, return_counts = True)
print(new_array)

[1 2 3 4 2 3 4 5 6 3 3 8 0 6 7]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([12,  0,  1,  2,  3,  7,  8, 14, 11], dtype=int64), array([1, 1, 2, 4, 2, 1, 2, 1, 1], dtype=int64))


In [94]:
#Delete
arr = np.array([[1,2,3,3],[4,5,6,7],[6,7,8,9]])
print(arr)
new_arr = np.delete(arr, 1, axis = 0)
print()
print(new_arr)

[[1 2 3 3]
 [4 5 6 7]
 [6 7 8 9]]

[[1 2 3 3]
 [6 7 8 9]]


In [96]:
arr = np.array([1,2,3,4,5])
print(arr)
arr1 = np.delete(arr, [2])
print(arr1)

[1 2 3 4 5]
[1 2 4 5]
